# nginx/Dockerfile

# Use a imagem oficial do Nginx como base
FROM nginx:stable-alpine

# Copie o seu arquivo de configuração local para o local correto dentro da imagem
COPY ./nginx.conf /etc/nginx/nginx.conf